---
loopback:
  ips:
    - "{{ vxlan_local_loopback }}"
eth0:
  ips:
    - "{{ eth0_ip }}"
bgp_interfaces:
  - swp1s0
  - swp1s1
  - swp2s0
  - swp2s1
  - swp3s0
  - swp3s1
  - swp4s0
  - swp4s1
  - swp5s0
  - swp5s1
  - swp6s0
  - swp6s1
  - swp7s0
  - swp7s1
  - swp8s0
  - swp8s1
netq:
  role: spine
adaptive_routing: true
routing_policies: true
route_map:
  - name: lo_subnet
    rules: 
      - id: 10 
        description: permit_lo_subnet
        action: permit
        match: interface
        match_param: lo
        type: ipv4
  - name: w_ecmp
    rules: 
      - id: 10 
        description: enable_w_ecmp
        action: permit
        set: ext-community-bw
        set_param: multipaths
interfaces:
  - name: swp1s0
    ar: true
  - name: swp1s1
    ar: true
  - name: swp2s0
    ar: true
  - name: swp2s1
    ar: true
  - name: swp3s0
    ar: true
  - name: swp3s1
    ar: true
  - name: swp4s0
    ar: true
  - name: swp4s1
    ar: true
  - name: swp5s0
    ar: true
  - name: swp5s1
    ar: true
  - name: swp6s0
    ar: true
  - name: swp6s1
    ar: true
  - name: swp7s0
    ar: true
  - name: swp7s1
    ar: true
  - name: swp8s0
    ar: true
  - name: swp8s1
    ar: true
vrfs:
  - "{{ vrf_mgmt }}"
bgp:
  asn: "{{ bgp_asn_prefix.spine }}100"
  router_id: "{{ vxlan_local_loopback | ansible.utils.ipaddr('address') }}"
  peergroups:
    - {name: underlay, description: underlay_switch_interconnect ,remote_as: external}
    - {name: overlay, description: overlay_interconnect ,remote_as: external, ttl: 2, src: lo}
  address_family:
    - name: ipv4_unicast
      redistribute:
        - {type: connected, route_map: lo_subnet}
      neighbors:
        - {interface: underlay, activate: true}
    - name: l2vpn_evpn
      neighbors:
        - {interface: overlay, activate: true}
  graceful_restart:
    mode: helper-only
  path_selection: 
    multipath: aspath-ignore
underlay_bfd:
  detect_multiplier: 3
  min_rx_interval: 300
  min_tx_interval: 300
overlay_bfd:
  detect_multiplier: 3
  min_rx_interval: 1000
  min_tx_interval: 1000
roce:
  mode: lossless
qos:
  pools:
    - name: default-lossy
      memory_percent: 10
    - name: roce-lossless  
      memory_percent: 90
  egress_scheduler:
    traffic_class:
      - name: 0
        bw_percent: 10
        mode: dwrr
      - name: 3
        bw_percent: 90
        mode: dwrr    
  pfc_wd: true