---
<<<<<<< HEAD
# - name: debug
#   debug:
#     msg: "{{ clear }}"
=======
#- name: debug
#  debug:
#    msg: "{{ clear }}"
>>>>>>> 99f2d64f3247924a0d1d8f8f0dfa66f1d1073d1a

- name: clear startup.yaml
  template:
    src: "clear.j2"
    dest: /etc/nvue.d/startup.yaml
    owner: nvue
    group: nvue
    mode: 0644
  when: clear=="1"

- name: copy startup.yaml
  template:
    src: "nvue.j2"
    dest: /etc/nvue.d/startup.yaml
    owner: nvue
    group: nvue
    mode: 0644
  when: clear==0

- name: nvue config replace
  ansible.builtin.shell: nv config replace /etc/nvue.d/startup.yaml

- name: nvue config apply
  ansible.builtin.shell: nv config apply -y

- name: nvue config save
  ansible.builtin.shell: nv config save

# - name: set switch role for netq
#   ansible.builtin.shell: netq lcm add {{ netq.role }} switches "{{ inventory_hostname }}" 

- name: Force all notified handlers to run at this point, not waiting for normal syn$
  meta: flush_handlers
