---
- name: Package installs
  apt:
    pkg:
      - lldpd
      - net-tools
      - traceroute
      - chrony
    state: present
  when: clear==0

- name: set hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"
    
### make sure to edit both dest files accoeding to the hgx netplan yaml files (e.g. 01-netcfg.yaml)
- name: Push mgmt_interface config to hgx
  template:
    src: mgmt_interface.j2
    dest: /etc/netplan/config.yaml
    mode: 0644
  notify: netplan apply
  when: clear==0

- name: Push gpu_ports config to hgx
  template:
    src: gpu_ports.j2
    dest: /etc/netplan/gpu_ports.yaml
    mode: 0644
  notify: netplan apply
  when: clear==0

- name: Copy IP addresses list for testing
  copy:
    src: ip_addresses.txt
    dest: /home/ubuntu
    mode: 0644
  when: inventory_hostname == "server01"

- name: Copy ping test script testing
  copy:
    src: ping.sh
    dest: /home/ubuntu
    mode: 0777
  when: inventory_hostname == "server01"

- name: notify
  meta: flush_handlers
